import { IMessageResponse } from "./MessageResponse";
import { Usuario } from "./Usuario";
import { Cabezote } from "./Cabezote";
import { Trailer } from "./Trailer";
import { Conductor } from "./Conductor";
import { Area } from "./Area";
import { Compañia } from "./Compañia";
import { Log } from "./Log";
import { Linea } from "./Linea";
import { Rol } from "./Rol";
import { Terminal } from "./Terminal";
import { Tanque } from "./Tanque";
import { Contador } from "./Contador";
import { Proveedor } from "./Proveedor";
import { MapeoArchivos } from "./ProcesamientoArchivos";
import { Producto } from "./Producto";
import { Despacho } from "./Despacho";
import { FechasCorteDTO } from "./FechasCorteDTO";

export const models = [Usuario, Cabezote, Trailer, Conductor, Area, Log, Rol, Compañia, Terminal, Tanque, Contador, Linea, Proveedor, MapeoArchivos, Producto, Despacho, FechasCorteDTO];

export * from "./MessageResponse";
export * from "./Usuario";
export * from "./Cabezote";
export * from "./Trailer";
export * from "./Conductor";
export * from "./Area";
export * from "./Linea";
export * from "./Compañia";
export * from "./Rol";
export * from "./Terminal";
export * from "./Tanque";
export * from "./Contador";
export * from "./Log";
export * from "./Proveedor";
export * from "./ProcesamientoArchivos";
export * from "./Producto";
export * from "./Despacho";
export * from "./FechasCorteDTO";
